import { useState } from 'react';
import {
  BookOpen,
  ChevronDown,
  ChevronRight,
  Database,
  Dna,
  FileSearch,
  FolderOpen,
  History,
  Layers,
  MousePointerClick,
  Play,
  Sparkles,
} from 'lucide-react';

interface Section {
  id: string;
  label: string;
  icon: React.ReactNode;
}

const SECTIONS: Section[] = [
  { id: 'getting-started',    label: 'Getting Started',           icon: <BookOpen className="w-4 h-4" /> },
  { id: 'running-search',     label: 'Running a Search',          icon: <Play className="w-4 h-4" /> },
  { id: 'understanding',      label: 'Understanding the Results', icon: <FileSearch className="w-4 h-4" /> },
  { id: 'history',            label: 'Search History',            icon: <History className="w-4 h-4" /> },
  { id: 'add-database',       label: 'Adding a Database',         icon: <Database className="w-4 h-4" /> },
  { id: 'add-representation', label: 'Adding a Representation',   icon: <Layers className="w-4 h-4" /> },
  { id: 'glossary',           label: 'Glossary',                  icon: <BookOpen className="w-4 h-4" /> },
];

function SectionHeader({ id, icon, title }: { id: string; icon: React.ReactNode; title: string }) {
  return (
    <div id={id} className="flex items-center gap-3 mb-4 scroll-mt-24">
      <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-teal-100 dark:bg-teal-900/40 text-[#0d5c6b] dark:text-teal-300 shrink-0">
        {icon}
      </div>
      <h2 className="text-xl font-semibold font-dm-sans text-gray-800 dark:text-gray-100">{title}</h2>
    </div>
  );
}

function Step({ n, children }: { n: number; children: React.ReactNode }) {
  return (
    <div className="flex gap-3">
      <div className="flex items-center justify-center w-6 h-6 rounded-full bg-[#0d5c6b] text-white text-xs font-semibold font-dm-sans shrink-0 mt-0.5">
        {n}
      </div>
      <p className="text-sm font-dm-sans text-gray-700 dark:text-gray-300 leading-relaxed">{children}</p>
    </div>
  );
}

function Param({ name, children }: { name: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-3 py-2 border-b border-gray-100 dark:border-gray-700/60 last:border-b-0">
      <span className="font-jetbrains-mono text-xs text-[#0d5c6b] dark:text-teal-300 shrink-0 pt-0.5 w-44">{name}</span>
      <span className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">{children}</span>
    </div>
  );
}

const GLOSSARY_TERMS: { term: string; definition: string }[] = [
  { term: 'FASTA', definition: 'Text format used to represent biological sequences.' },
  { term: 'BLAST', definition:'Tool used to find proteins with similar sequences.'},
  { term: 'HMMER', definition:'Tool used to identify domains or protein families using profile models.'},
  { term: 'Pfam', definition:'Database of protein families and domains.'},
  { term: 'PDB', definition:'Database of protein structures and protein-ligand complexes.'},
  { term: 'ChEMBL', definition:'Database of chemical bioactivity information.'},
  { term: 'ZINC', definition:'Database of commercially available or screenable compounds.'},
  { term: 'LOTUS', definition:'Database of natural products and related compounds.'},
  { term: 'Fingerprint', definition: 'Binary vector summarizing structural features of molecule.' },
  { term: 'Embedding', definition: 'Continuous vector generated by a machine learning model.' },
  { term: 'Tanimoto', definition: 'Common metric for comparing binary fingerprints.' },
  { term: 'Cosine similarity', definition: 'Common metric for comparing continuous embeddings.' },
  { term: 'Known ligands', definition: 'Compounds with experimental binding evidence from PDB crystal structures or ChEMBL bioactivity records.' },
  { term: 'Predicted ligands', definition: 'Compounds retrieved from the search database by structural similarity to known ligands. No direct experimental evidence for the query protein.' },
  { term: 'Search threshold', definition: 'Minimum similarity score (Tanimoto or Cosine) required to include a compound in the predicted ligands output.' },
  { term: 'Representation',  definition: 'Numerical encoding of a molecule computed from its SMILES structure. Examples: Morgan fingerprint, MACCS keys, ChemBERTa embedding.' },
  { term: 'SMILES', definition: 'Simplified Molecular Input Line Entry System — a text notation encoding a molecular structure as a linear string.' },
  { term: 'Sequence search', definition: 'Uses BLAST to find proteins in PDB/ChEMBL with high sequence identity to the query protein.' },
  { term: 'Nearest K search', definition: 'Retrieves the K most similar proteins in the embedding space regardless of a fixed threshold.' },
  { term: 'Domain search',   definition: 'Uses HMMER to find proteins sharing conserved protein domains with the query.' },
];

function GlossaryItem({ term, definition }: { term: string; definition: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-gray-100 dark:border-gray-700/60 last:border-b-0">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between py-3 text-left gap-4 cursor-pointer"
      >
        <span className="font-dm-sans font-medium text-sm text-gray-800 dark:text-gray-100">{term}</span>
        {open
          ? <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />
          : <ChevronRight className="w-4 h-4 text-gray-400 shrink-0" />
        }
      </button>
      {open && (
        <p className="pb-3 text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed pl-0">
          {definition}
        </p>
      )}
    </div>
  );
}

function Card({ children }: { children: React.ReactNode }) {
  return (
    <div className="bg-gray-50 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700 rounded-xl p-5 flex flex-col gap-3">
      {children}
    </div>
  );
}

function InfoBadge({ label, color = 'teal' }: { label: string; color?: 'teal' | 'amber' | 'blue' | 'green' | 'red' }) {
  const cls: Record<string, string> = {
    teal:  'bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-300',
    amber: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
    blue:  'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
    green: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300',
    red:   'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
  };
  return (
    <span className={`inline-block px-2 py-0.5 rounded text-xs font-medium font-dm-sans ${cls[color]}`}>
      {label}
    </span>
  );
}

export function HelpPage() {
  const scrollTo = (id: string) => {
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return (
    <div className="flex h-[calc(100vh-80px)] overflow-hidden">
      {/* Sidebar */}
      <aside className="w-60 shrink-0 border-r border-gray-200 dark:border-gray-700/60 bg-gray-50 dark:bg-[#1a2330] overflow-y-auto py-6 px-4">
        <p className="text-xs font-semibold uppercase tracking-widest text-gray-400 dark:text-gray-500 mb-3 px-2">
          Contents
        </p>
        <nav className="flex flex-col gap-0.5">
          {SECTIONS.map((s) => (
            <button
              key={s.id}
              onClick={() => scrollTo(s.id)}
              className="flex items-center gap-2.5 px-2 py-2 rounded-lg text-left text-sm font-dm-sans
                text-gray-600 dark:text-gray-400 hover:text-[#0d5c6b] dark:hover:text-teal-300
                hover:bg-teal-50 dark:hover:bg-teal-900/20 transition-colors cursor-pointer"
            >
              <span className="text-gray-400 dark:text-gray-500">{s.icon}</span>
              {s.label}
            </button>
          ))}
        </nav>
      </aside>

      {/* Content */}
      <main className="flex-1 overflow-y-auto py-10 px-10">
        <div className="max-w-2xl mx-auto flex flex-col gap-12">

          {/* ── 1. Getting Started ── */}
          <section>
            <SectionHeader id="getting-started" icon={<BookOpen className="w-4 h-4" />} title="Getting Started" />
            <div className="flex flex-col gap-4">
              <p className="text-sm font-dm-sans text-gray-700 dark:text-gray-300 leading-relaxed">
                LigQ 2 helps you prioritize candidate ligands for a set of proteins of interest. You upload a
                FASTA file, and the system finds structurally similar proteins in PDB/ChEMBL, collects their known
                ligands, and retrieves compounds from external databases with high molecular similarity.
              </p>
            </div>
          </section>

          {/* ── 2. Running a Search ── */}
          <section>
            <SectionHeader id="running-search" icon={<Play className="w-4 h-4" />} title="Running a Search" />
            <div className="flex flex-col gap-4">
              <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                Click <strong className="text-gray-700 dark:text-gray-200">Visualize Results</strong> in the top
                navigation bar to access the search interface.
              </p>

              <Card>
                <div className="flex items-center gap-2 text-sm font-semibold font-dm-sans text-gray-700 dark:text-gray-200">
                  <MousePointerClick className="w-4 h-4 text-[#0d5c6b] dark:text-teal-300" />
                  Search Parameters (left sidebar)
                </div>
                <div className="flex flex-col divide-y divide-gray-100 dark:divide-gray-700/60">
                  <Param name="Search database">
                    Select a processed compound database (e.g. ZINC, LOTUS, or a custom database you added).
                  </Param>
                  <Param name="Representation">
                    Molecular fingerprint or embedding used for similarity comparison (e.g. Morgan 1024, MACCS).
                  </Param>
                  <Param name="Metric">
                    Auto-detected from the representation.{' '}
                    <InfoBadge label="Tanimoto" color="teal" /> for binary fingerprints,{' '}
                    <InfoBadge label="Cosine" color="blue" /> for embeddings.
                  </Param>
                  <Param name="Min / Max cutoff">
                    Similarity threshold for predicted ligands. Only compounds with similarity inside this range
                    are included (0.0 to 1.0). The minimum uses the selected representation's pipeline default,
                    rounded upward to two decimals; representations without a registered default start at 0.9.
                    The maximum starts at 1.0, and both controls advance in 0.01 increments.
                  </Param>
                  <Param name="Input FASTA">
                    Click the folder icon to upload your <span className="font-jetbrains-mono text-xs">.fasta</span>,{' '}
                    <span className="font-jetbrains-mono text-xs">.fa</span>, or{' '}
                    <span className="font-jetbrains-mono text-xs">.faa</span> file.
                    Each sequence in the file becomes one query.
                  </Param>
                  <Param name="Method">
                    Check one or more search strategies:{' '}
                    <InfoBadge label="Sequence" color="teal" /> (BLAST),{' '}
                    <InfoBadge label="Nearest K" color="blue" /> (set K),{' '}
                    <InfoBadge label="Domain" color="amber" /> (HMMER).
                  </Param>
                </div>
              </Card>

              <div className="flex flex-col gap-2">
                <Step n={1}>Select your database, representation, and similarity cutoffs.</Step>
                <Step n={2}>Upload a FASTA file using the folder icon in the sidebar.</Step>
                <Step n={3}>Choose at least one search method (Sequence, Nearest K, or Domain).</Step>
                <Step n={4}>
                  Click <strong>Run Search</strong>. The status panel shows the current step, processed items,
                  ETA, and elapsed time. Results appear progressively as each query completes.
                </Step>
                <Step n={5}>
                  Collapse the sidebar with the{' '}
                  <span className="font-jetbrains-mono text-xs bg-gray-100 dark:bg-gray-800 px-1 rounded">{'<'}</span>{' '}
                  button on its right edge to get more screen space for results.
                </Step>
              </div>
            </div>
          </section>

          {/* ── 3. Understanding the Results ── */}
          <section>
            <SectionHeader id="understanding" icon={<FileSearch className="w-4 h-4" />} title="Understanding the Results" />
            <div className="flex flex-col gap-5">

              <div>
                <h3 className="text-sm font-semibold font-dm-sans text-gray-700 dark:text-gray-200 mb-2">Metric cards</h3>
                <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                  The four cards at the top summarise the current search run: total Queries, proteins in the
                  Protein Ranking, Known Bindings, and Predicted Ligands. Hover over any number to see a
                  breakdown by search method (sequence / nearest K / domain).
                </p>
              </div>

              <div>
                <h3 className="text-sm font-semibold font-dm-sans text-gray-700 dark:text-gray-200 mb-2">Queries table</h3>
                <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed mb-2">
                  Each row represents one sequence from your FASTA. Status badges indicate progress:
                </p>
                <div className="flex flex-wrap gap-2 mb-3">
                  <InfoBadge label="Completed" color="green" />
                  <InfoBadge label="Running" color="teal" />
                  <InfoBadge label="Queued" color="amber" />
                  <InfoBadge label="Failed" color="red" />
                  <InfoBadge label="Completed with warnings" color="amber" />
                </div>
                <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                  Click a query row to load its results below. Use the{' '}
                  <strong className="text-gray-700 dark:text-gray-200">Protein Ranking</strong>,{' '}
                  <strong className="text-gray-700 dark:text-gray-200">Known Bindings</strong>, or{' '}
                  <strong className="text-gray-700 dark:text-gray-200">Predicted Ligands</strong> buttons on the
                  row to jump directly to that tab.
                </p>
              </div>

              <div>
                <h3 className="text-sm font-semibold font-dm-sans text-gray-700 dark:text-gray-200 mb-2">Results panel</h3>
                <Card>
                  <div className="flex flex-col divide-y divide-gray-100 dark:divide-gray-700/60">
                    <Param name="Protein Ranking">
                      Candidate proteins ranked by BLAST bitscore or HMMER domain score. Shows identity,
                      coverage, and e-value for each hit.
                    </Param>
                    <Param name="Known Bindings">
                      Ligands from PDB crystal structures or ChEMBL bioactivity records associated with the
                      candidate proteins. Includes pChEMBL potency and binding-site Pfam domains where available.
                    </Param>
                    <Param name="Predicted Ligands">
                      Compounds retrieved from the search database by structural similarity to known ligands.
                      Each row shows the Tanimoto (or Cosine) score and the query/hit protein pair.
                    </Param>
                  </div>
                </Card>
              </div>

              <div>
                <h3 className="text-sm font-semibold font-dm-sans text-gray-700 dark:text-gray-200 mb-2">Selected result panel</h3>
                <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                  Click any row in the Known Bindings or Predicted Ligands table to open the detail panel on
                  the right. It shows compound metadata, the full SMILES string, a 2D structure preview, and
                  two action buttons:
                </p>
                <ul className="mt-2 list-disc list-inside text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed space-y-1 pl-1">
                  <li><strong className="text-gray-700 dark:text-gray-200">Download SDF</strong> — saves the compound as a structure file.</li>
                  <li><strong className="text-gray-700 dark:text-gray-200">Open in Viewer</strong> — opens an interactive 3D structure viewer.</li>
                </ul>
              </div>
            </div>
          </section>

          {/* ── 4. Search History ── */}
          <section>
            <SectionHeader id="history" icon={<History className="w-4 h-4" />} title="Search History" />
            <div className="flex flex-col gap-4">
              <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                LigQ 2 stores every search run on disk. You can reload any previous run without re-running
                the pipeline.
              </p>
              <div className="flex flex-col gap-2">
                <Step n={1}>
                  Click the <strong>History</strong> button at the top right of the Visualize Results view.
                </Step>
                <Step n={2}>
                  A dropdown lists all past runs, each identified by a job ID and timestamp.
                </Step>
                <Step n={3}>
                  Click <strong>Load</strong> next to any run to restore its full results instantly.
                </Step>
              </div>
              <p className="text-xs font-dm-sans text-gray-400 dark:text-gray-500">
                Results are stored under{' '}
                <span className="font-jetbrains-mono">results/{'<job_id>'}/search_results/</span> in the
                project directory.
              </p>
            </div>
          </section>

          {/* ── 5. Adding a Database ── */}
          <section>
            <SectionHeader id="add-database" icon={<Database className="w-4 h-4" />} title="Adding a New Database" />
            <div className="flex flex-col gap-4">
              <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                Any compound file you own can be imported and searched. Go to{' '}
                <strong className="text-gray-700 dark:text-gray-200">Configure Search → Add new database</strong>.
              </p>
              <div className="flex flex-col gap-2">
                <Step n={1}>
                  Drag and drop your file into the upload area, or click{' '}
                  <strong>Browse files</strong>. Supported formats:{' '}
                  <InfoBadge label=".smi" /> <InfoBadge label=".csv" color="blue" />{' '}
                  <InfoBadge label=".tsv" color="blue" /> <InfoBadge label=".parquet" color="blue" />
                </Step>
                <Step n={2}>
                  For CSV, TSV, or Parquet files, select the <strong>Compound ID column</strong> and the
                  <strong> SMILES column</strong> from the dropdown menus that appear after upload.
                </Step>
                <Step n={3}>
                  Set the <strong>Output directory name</strong> — lowercase letters, digits, and underscores
                  only (e.g. <span className="font-jetbrains-mono text-xs">my_library</span>).
                </Step>
                <Step n={4}>
                  Click <strong>Process database</strong>. The status panel reports indexing and fingerprint
                  progress; the default Morgan representation is built automatically.
                </Step>
                <Step n={5}>
                  Once complete, the new database appears immediately in the Search sidebar dropdown.
                </Step>
              </div>
            </div>
          </section>

          {/* ── 6. Adding a Representation ── */}
          <section>
            <SectionHeader id="add-representation" icon={<Layers className="w-4 h-4" />} title="Adding a New Representation" />
            <div className="flex flex-col gap-4">
              <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400 leading-relaxed">
                Each database can have multiple representations. Adding more representations lets you search with
                different similarity metrics. Go to{' '}
                <strong className="text-gray-700 dark:text-gray-200">Configure Search → Add new representation</strong>.
              </p>
              <div className="flex flex-col gap-2">
                <Step n={1}>Select the database you want to add the representation to.</Step>
                <Step n={2}>
                  Choose a <strong>Representation type</strong>:{' '}
                  <InfoBadge label="RDKit fingerprint" color="teal" /> or{' '}
                  <InfoBadge label="HuggingFace embedding" color="blue" />
                </Step>
                <Step n={3}>
                  Choose a <strong>Representation preset</strong>. The recommended metric (Tanimoto or Cosine)
                  is set automatically.
                </Step>
                <Step n={4}>
                  The <strong>Representation name</strong> is auto-generated from the preset and parameters.
                  Using the canonical name (shown as placeholder) ensures automatic similarity thresholds work
                  correctly in search runs.
                </Step>
                <Step n={5}>
                  Click <strong>Process representation</strong>. This computes fingerprints or embeddings for
                  every compound in the database while showing the active database, count, ETA, and elapsed time.
                  <span className="ml-1 text-amber-600 dark:text-amber-400">
                    RDKit fingerprints take minutes; HuggingFace embeddings may take several hours on large databases.
                  </span>
                </Step>
                <Step n={6}>
                  When complete, the new representation appears in the Search sidebar Representation dropdown.
                </Step>
              </div>

              <Card>
                <div className="flex items-center gap-2 text-sm font-semibold font-dm-sans text-gray-700 dark:text-gray-200">
                  <Sparkles className="w-4 h-4 text-[#0d5c6b] dark:text-teal-300" />
                  Available presets
                </div>
                <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs font-dm-sans">
                  {[
                    ['ECFP Morgan',       'RDKit', 'Tanimoto'],
                    ['MACCS',             'RDKit', 'Tanimoto'],
                    ['RDKit fingerprint', 'RDKit', 'Tanimoto'],
                    ['Morgan Feature',    'RDKit', 'Tanimoto'],
                    ['Atom Pair',         'RDKit', 'Tanimoto'],
                    ['Topol. Torsion',    'RDKit', 'Tanimoto'],
                    ['ChemBERTa (ZINC)',  'HuggingFace', 'Cosine'],
                    ['ChemBERTa (PubChem)', 'HuggingFace', 'Cosine'],
                  ].map(([name, type, metric]) => (
                    <div key={name} className="flex items-center justify-between py-1 border-b border-gray-100 dark:border-gray-700/40">
                      <span className="text-gray-700 dark:text-gray-300 font-medium">{name}</span>
                      <div className="flex gap-1">
                        <InfoBadge label={type} color={type === 'RDKit' ? 'teal' : 'blue'} />
                        <InfoBadge label={metric} color="amber" />
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            </div>
          </section>

          {/* ── 7. Glossary ── */}
          <section>
            <SectionHeader id="glossary" icon={<Dna className="w-4 h-4" />} title="Glossary" />
            <div className="flex flex-col gap-3">
              <p className="text-sm font-dm-sans text-gray-600 dark:text-gray-400">
                Click a term to expand its definition.
              </p>
              <div className="bg-gray-50 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700 rounded-xl px-5 py-1">
                {GLOSSARY_TERMS.map((t) => (
                  <GlossaryItem key={t.term} term={t.term} definition={t.definition} />
                ))}
              </div>
            </div>
          </section>

          {/* Footer spacer */}
          <div className="flex items-center gap-3 py-6 border-t border-gray-100 dark:border-gray-700/60">
            <FolderOpen className="w-4 h-4 text-gray-300 dark:text-gray-600" />
            <p className="text-xs font-dm-sans text-gray-400 dark:text-gray-600">
              LigQ 2 — Ligand Prioritization from Protein Sequences
            </p>
          </div>

        </div>
      </main>
    </div>
  );
}
